### ISSUE TITLE
Add endpoints to retrieve interoperability data from the node to LIP 0045

### ISSUE THREAD

**Issue by Tschakki** [LiskHQ/lips#230]
### Description
While writing the guide "How to register a sidechain", I wanted to explain to the reader, how to check the status of their sidechain by getting the sidechain account.
I was surprised to not find any existing endpoints for this.
As it turns out, this functionality is currently not built-in in the Interoperability module and it's related LIP 0045.

From user and docs perspective, I consider such an endpoint quite relevant -  how else can they check about the status of a sidechain?

It would be also great if it could be reconsidered as part of this issue to add other similar endpoints to the module, too, which provide relevant data to the users. Please try to look at it from a users perspective.
E.g. a list of all chain IDs of sidechains that are registered on the Mainchain would be interesting as well, imho.

**Comment by ricott1** [comment]
Hello @Tschakki,

In order to keep LIPs lean and avoid content duplication, we decided to not explicitly add 'trivial' endpoints to our LIPs. This means, for instance, that the endpoints to get the Interoperability substores entries are not in LIP 45. This does not mean that they should not exist in the implementation (maybe @ishantiw can point you to the place in the SDK).

**Comment by ishantiw** [comment]
We can get all the registered module endpoints by calling `system_getMetadata`, for example, we have `interoperability_getChainAccount`, `interoperability_getAllChainAccounts`, etc which you can find in the code [here](https://github.com/LiskHQ/lisk-sdk/blob/development/framework/src/modules/interoperability/base_interoperability_endpoint.ts).

As @ricott1 pointed out above, since endpoints are not protocol but rather UX, its hard to put on the exact specification in LIPs and maybe LIP should only point out some necessary endpoints and leave rest up to the SDK.
