### ISSUE TITLE
LIP0045 & LIP0051: Remove some redundant constants

### ISSUE THREAD

**Issue by sitetester** [LiskHQ/lips#326]
- `TOKEN_ID_LENGTH` this constant is relevant to Token module (LIP 51), we can remove it from LIP 45
- `CHAIN_ID_LENGTH` this constant is relevant to interoperability module (LIP 45), we can remove it from LIP 51
- `SUBSTORE_PREFIX_LENGTH` from LIP 45 can be removed, already defined in LIP 40 & indeed it's relevant to state model. After we make this change, can give a reference to this constant in LIPs 45 & 54 (from LIP 40).

This will also involve removing corresponding `Type Definition` entries.

**Comment by gkoumout** [comment]
Three more points to finish this conversation:

 - We have agreed to have all general constants used in a LIP defined there. I see no serious reason to change this now, at this stage. The interoperability LIPs are an exception since it is one module described in 5 LIPs and in all LIPs (43,49,53,54) we explicitly mention that all constants used are defined in LIP 45, making it easy to recover them. For general constants, that would not be possible.
 - In case in future we want to update some constants, we need to edit all LIPs where it is used anyways, so I don't think this makes the task easier anyways. The only advantage is that the LIPs would get shorted, but at the expense of making harder for the reader to find where each constant is defined.
 - In fact the constant `SUBSTORE_PREFIX_LENGTH` should not be removed from LIP 45 either, since it is used in LIP 54.
